# Generated by Django 5.1.3 on 2026-04-07 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0002_alter_medicine_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicine',
            name='dosage',
            field=models.CharField(max_length=128),
        ),
    ]
